version: '3'

services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      TZ: Asia/Chongqing
    volumes:
      - zs-example-db:/var/lib/mysql
    # ports:
    #   - "3806:3306"

  redis:
    image: redis

  web:
    image: zs-example
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ".:/app:rw"
    command: ["pipenv", "run", "flask", "run", "-h", "0.0.0.0"]

  celery:
    image: zs-example
    depends_on:
      - db
      - redis
    volumes:
      - ".:/app:rw"
    command: ["pipenv", "run", "celery", "-A", "demo.celery_worker", "worker", "--loglevel=INFO"]

volumes:
  zs-example-db:
    driver: local